/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.IUC;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class addCUPanel extends javax.swing.JPanel {

    private static final String YEAR = "º ano";
    private static final String SEMESTER = "º semestre";
    
    private boolean checked;
    private final String name;
    
    
    public addCUPanel(IUC uc) {
        initComponents();
        yearLabel.setText(uc.getAno() + YEAR);
        semesterLabel.setText(uc.getSemestre() + SEMESTER);
        cuLabel.setText(uc.getNome());
        checked = false;
        name = uc.getNome();
        this.styleComponents();
    }

    
    public boolean isChecked() {
        return checked;
    }
    
    
    public String getName() {
        return name;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        cuLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 54, 76));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 45));
        setPreferredSize(new java.awt.Dimension(400, 45));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        yearLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("jLabel1");

        semesterLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(255, 255, 255));
        semesterLabel.setText("jLabel2");

        cuLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cuLabel.setText("jLabel3");
        cuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(yearLabel)
                .addGap(36, 36, 36)
                .addComponent(semesterLabel)
                .addGap(29, 29, 29)
                .addComponent(cuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(semesterLabel)
                    .addComponent(cuLabel))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!checked) {
            this.setBackground(Color.decode(ThemeColors.BLUE_COLOR));
            checked = true;
        } else {
            this.setBackground(Color.decode(ThemeColors.DARK_COLOR));
            checked = false;
        }
    }//GEN-LAST:event_formMouseClicked

    
    private void styleComponents() {
        this.setBorder(new MatteBorder(
                        0, 0, 1, 0, Color.decode(ThemeColors.BORDER_COLOR)));
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuLabel;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
