/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.BusinessFacade;
import Business.IUC;
import java.awt.Color;
import java.util.List;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class CUPanel extends javax.swing.JPanel {

    private static final String YEAR = "º ano";
    private static final String SEMESTER = "º semestre";
    private static final String NO_SHIFTS = "--";
    
    
    private final BusinessFacade bFacade;
    private final String uc;
    private final List<String> shifts;
    private final boolean classesStarted;
    
    
    public CUPanel(BusinessFacade bFacade, String uc,
            List<String> shifts, boolean classesStarted) {
        this.classesStarted = classesStarted;
        initComponents();
        this.shifts = shifts;
        this.bFacade = bFacade;
        this.uc = uc;
        this.styleComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        cuLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(45, 54, 76));
        setMaximumSize(new java.awt.Dimension(500, 32767));
        setName(""); // NOI18N

        yearLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("jLabel1");

        semesterLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(255, 255, 255));
        semesterLabel.setText("jLabel2");

        cuLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cuLabel.setText("jLabel3");
        cuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        shiftLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shiftLabel.setText("jLabel4");
        shiftLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        modifyButton.setBackground(new java.awt.Color(88, 144, 255));
        modifyButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Modificar");
        modifyButton.setContentAreaFilled(false);
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyButton.setOpaque(true);
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearLabel)
                .addGap(18, 18, 18)
                .addComponent(semesterLabel)
                .addGap(18, 18, 18)
                .addComponent(cuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftLabel)
                .addGap(25, 25, 25)
                .addComponent(modifyButton)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(semesterLabel)
                    .addComponent(cuLabel)
                    .addComponent(shiftLabel)
                    .addComponent(modifyButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        ChangeShiftFrame c = new ChangeShiftFrame(bFacade, uc, shifts);
        c.setVisible(true);
    }//GEN-LAST:event_modifyButtonMouseClicked

    
    private void styleComponents() {
        this.setBorder(new MatteBorder(
                0, 0, 3, 0, Color.decode(ThemeColors.BLUE_COLOR)));
        
        IUC iuc = bFacade.getUCInfo(uc);
        yearLabel.setText(iuc.getAno() + YEAR);
        semesterLabel.setText(iuc.getSemestre() + SEMESTER);
        cuLabel.setText(iuc.getNome());
        
        String str;
        StringBuilder sb = new StringBuilder("");
                
        for (int j = 0; j < shifts.size(); j++) {
            sb.append(shifts.get(j));

            if (j != shifts.size() - 1) {
                sb.append("/");
            }
        }

        str = sb.toString();

        if (str.equals("")) {
            str = NO_SHIFTS;
            modifyButton.setVisible(false);
        }
        
        shiftLabel.setText(str);
        
        if (classesStarted) {
            modifyButton.setVisible(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuLabel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
