/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.BusinessFacade;
import Business.IUC;
import Business.Pair;
import java.awt.Color;
import java.util.List;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class LogPanel extends javax.swing.JPanel {

    private static final String YEAR = "º ano";
    private static final String SEMESTER = "º semestre";
    
    
    private final BusinessFacade bFacade;
    private final String uc;
    private final String turno;
    
    
    public LogPanel(BusinessFacade bFacade, String uc, String turno) {
        this.bFacade = bFacade;
        this.uc = uc;
        this.turno = turno;
        initComponents();
        this.styleComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        cuLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        cButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(45, 54, 76));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        yearLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("jLabel1");

        semesterLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(255, 255, 255));
        semesterLabel.setText("jLabel2");

        cuLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cuLabel.setText("jLabel3");
        cuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        shiftLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shiftLabel.setText("jLabel4");
        shiftLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cButton.setBackground(new java.awt.Color(88, 144, 255));
        cButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cButton.setForeground(new java.awt.Color(255, 255, 255));
        cButton.setText("Consultar");
        cButton.setContentAreaFilled(false);
        cButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cButton.setOpaque(true);
        cButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearLabel)
                .addGap(18, 18, 18)
                .addComponent(semesterLabel)
                .addGap(18, 18, 18)
                .addComponent(cuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftLabel)
                .addGap(25, 25, 25)
                .addComponent(cButton)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(semesterLabel)
                    .addComponent(cuLabel)
                    .addComponent(shiftLabel)
                    .addComponent(cButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseClicked
        LogFrame l = new LogFrame(bFacade, uc, turno);
        l.setVisible(true);
    }//GEN-LAST:event_cButtonMouseClicked


    private void styleComponents() {
        this.setBorder(new MatteBorder(
                0, 0, 3, 0, Color.decode(ThemeColors.BLUE_COLOR)));
        
        IUC iuc = bFacade.getUCInfo(uc);
        yearLabel.setText(iuc.getAno() + YEAR);
        semesterLabel.setText(iuc.getSemestre() + SEMESTER);
        cuLabel.setText(iuc.getNome());
        
        shiftLabel.setText(turno);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cButton;
    private javax.swing.JLabel cuLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
