/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.BusinessFacade;
import Business.Pair;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class MClassesPanel extends javax.swing.JPanel {

    private final BusinessFacade bFacade;
    private final String uc;
    private final String turno;
    private final Pair<String, Integer> aluno;
    
    
    public MClassesPanel(BusinessFacade bFacade, String uc, String turno, 
            Pair<String, Integer> aluno) {
        this.bFacade = bFacade;
        this.uc = uc;
        this.turno = turno;
        this.aluno = aluno;
        initComponents();
        this.styleComponents();
    }

    
    public String getUC() {
        return uc;
    }
    
    
    public String getTurno() {
        return turno;
    }
    
    
    public String getAluno() {
        return aluno.getLeft();
    }
    
    
    public int getFaltas() {
        int n = 0;
        
        try {
            n = Integer.parseInt(mText.getText());
            
            if (n < 0 || 
                    (aluno.getRight() + n) > bFacade.getAulasTurno(uc, turno)) {
                n = 0;
            }
        } catch (NumberFormatException e) {
            n = 0;
        }
        
        return n;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        mText = new javax.swing.JTextField();
        mLabel = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(45, 54, 76));

        studentLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        studentLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentLabel.setText("jLabel1");

        mText.setBackground(new java.awt.Color(45, 54, 76));
        mText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mText.setForeground(new java.awt.Color(255, 255, 255));
        mText.setText("0");
        mText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 43, 62)));
        mText.setCaretColor(new java.awt.Color(255, 255, 255));

        mLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mLabel.setForeground(new java.awt.Color(255, 255, 255));
        mLabel.setText("Faltou a 25% das aulas");

        removeButton.setBackground(new java.awt.Color(88, 144, 255));
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remover");
        removeButton.setContentAreaFilled(false);
        removeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeButton.setOpaque(true);
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(studentLabel)
                .addGap(18, 18, 18)
                .addComponent(mText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(mLabel)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLabel)
                    .addComponent(mText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mLabel)
                    .addComponent(removeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        bFacade.removeAlunoTurno(uc, turno, aluno.getLeft());
        bFacade.writeLog(uc, turno, "Removido o aluno " + aluno);
    }//GEN-LAST:event_removeButtonMouseClicked


    private void styleComponents() {
        mText.setBorder(BorderFactory.createCompoundBorder(
            mText.getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        
        this.setBorder(new MatteBorder(
                        0, 0, 1, 0, Color.decode(ThemeColors.BORDER_COLOR)));
        
        studentLabel.setText(aluno.getLeft());
        
        int numAulas = bFacade.getAulasTurno(uc, turno);
        
        if (aluno.getRight() == 0 || (numAulas / aluno.getRight() > 4)) {
            removeButton.setVisible(false);
            mLabel.setVisible(false);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mLabel;
    private javax.swing.JTextField mText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel studentLabel;
    // End of variables declaration//GEN-END:variables
}
