/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.BusinessFacade;
import Business.IUC;
import java.awt.Color;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class MCUPanel extends javax.swing.JPanel {

    private static final String YEAR = "º ano";
    private static final String SEMESTER = "º semestre";
    
    
    private final BusinessFacade bFacade;
    private final String uc;
    private final String turno;
    private boolean isSelected;
    
    
    public MCUPanel(BusinessFacade bFacade, String uc, String turno) {
        this.bFacade = bFacade;
        this.uc = uc;
        this.turno = turno;
        isSelected = false;
        initComponents();
        this.styleComponents();
    }

    
    public String getUC() {
        return uc;
    }
    
    
    public String getTurno() {
        return turno;
    }
    
    
    public boolean isSelected() {
        return isSelected;
    }
    
    
    public void unSelect() {
        isSelected = false;
    }
    
    
    public void setSelected() {
        if (isSelected) {
            isSelected = false;
        } else {
            isSelected = true;
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        cuLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(45, 54, 76));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        yearLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("jLabel1");

        semesterLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(255, 255, 255));
        semesterLabel.setText("jLabel2");

        cuLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cuLabel.setText("jLabel3");
        cuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        shiftLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shiftLabel.setText("jLabel4");
        shiftLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        modifyButton.setBackground(new java.awt.Color(88, 144, 255));
        modifyButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Marcar Faltas");
        modifyButton.setContentAreaFilled(false);
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modifyButton.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearLabel)
                .addGap(18, 18, 18)
                .addComponent(semesterLabel)
                .addGap(18, 18, 18)
                .addComponent(cuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftLabel)
                .addGap(25, 25, 25)
                .addComponent(modifyButton)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(semesterLabel)
                    .addComponent(cuLabel)
                    .addComponent(shiftLabel)
                    .addComponent(modifyButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void styleComponents() {
        this.setBorder(new MatteBorder(
                0, 0, 3, 0, Color.decode(ThemeColors.BLUE_COLOR)));
        
        IUC iuc = bFacade.getUCInfo(uc);
        yearLabel.setText(iuc.getAno() + YEAR);
        semesterLabel.setText(iuc.getSemestre() + SEMESTER);
        cuLabel.setText(iuc.getNome());
        
        shiftLabel.setText(turno);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuLabel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
