/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.BusinessFacade;
import java.awt.Color;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class RequestState extends javax.swing.JPanel {

    private final BusinessFacade bFacade;
    private final String uc;
    private final String to;
    
    
    public RequestState(BusinessFacade bFacade, String uc, String from, 
            String to, int index) {
        this.bFacade = bFacade;
        this.uc = uc;
        this.to = to;
        initComponents();
        cuLabel.setText(uc);
        fromLabel.setText(from);
        toLabel.setText(to);
        indexLabel.setText(String.valueOf(index));
        this.styleComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cuLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        indexLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(45, 54, 76));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 0));
        jPanel1.setName(""); // NOI18N

        cuLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cuLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuLabel.setText("jLabel1");

        fromLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fromLabel.setForeground(new java.awt.Color(255, 255, 255));
        fromLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fromLabel.setText("jLabel2");

        toLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        toLabel.setForeground(new java.awt.Color(255, 255, 255));
        toLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toLabel.setText("jLabel3");
        toLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        indexLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        indexLabel.setForeground(new java.awt.Color(255, 255, 255));
        indexLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indexLabel.setText("jLabel4");
        indexLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cancelButton.setBackground(new java.awt.Color(88, 144, 255));
        cancelButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setOpaque(true);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cuLabel)
                .addGap(28, 28, 28)
                .addComponent(fromLabel)
                .addGap(29, 29, 29)
                .addComponent(toLabel)
                .addGap(42, 42, 42)
                .addComponent(indexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuLabel)
                    .addComponent(fromLabel)
                    .addComponent(toLabel)
                    .addComponent(indexLabel)
                    .addComponent(cancelButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        CancelRequestFrame c = new CancelRequestFrame(bFacade, uc, to);
        c.setVisible(true);
    }//GEN-LAST:event_cancelButtonMouseClicked

    
    private void styleComponents() {
        this.setBorder(new MatteBorder(
                0, 0, 3, 0, Color.decode(ThemeColors.BLUE_COLOR)));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cuLabel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel indexLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
