/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.BusinessFacade;
import Business.IUC;
import java.awt.Color;
import javax.swing.border.MatteBorder;

/**
 *
 * @author rafae
 */
public class TCUPanel extends javax.swing.JPanel {

    private static final String YEAR = "º ano";
    private static final String SEMESTER = "º semestre";
    
    private final BusinessFacade bFacade;
    private final String uc;
    private final String turno;
    private final boolean classesStarted;
    
    
    
    public TCUPanel(BusinessFacade bFacade, String uc, String turno, 
            boolean classesStarted) {
        this.bFacade = bFacade;
        this.uc = uc;
        this.turno = turno;
        this.classesStarted = classesStarted;
        initComponents();
        this.styleComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        cuLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(45, 54, 76));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel1.setName(""); // NOI18N

        yearLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("jLabel1");

        semesterLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(255, 255, 255));
        semesterLabel.setText("jLabel2");

        cuLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cuLabel.setForeground(new java.awt.Color(255, 255, 255));
        cuLabel.setText("jLabel3");
        cuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        shiftLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shiftLabel.setText("jLabel4");
        shiftLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        modifyButton.setBackground(new java.awt.Color(88, 144, 255));
        modifyButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Gerir");
        modifyButton.setContentAreaFilled(false);
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyButton.setOpaque(true);
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearLabel)
                .addGap(18, 18, 18)
                .addComponent(semesterLabel)
                .addGap(18, 18, 18)
                .addComponent(cuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftLabel)
                .addGap(25, 25, 25)
                .addComponent(modifyButton)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(semesterLabel)
                    .addComponent(cuLabel)
                    .addComponent(shiftLabel)
                    .addComponent(modifyButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        ShiftManagerFrame s = new ShiftManagerFrame(bFacade, uc, turno, 
                classesStarted);
        s.setVisible(true);
    }//GEN-LAST:event_modifyButtonMouseClicked


    private void styleComponents() {
        this.setBorder(new MatteBorder(
                0, 0, 3, 0, Color.decode(ThemeColors.BLUE_COLOR)));
        
        IUC iuc = bFacade.getUCInfo(uc);
        yearLabel.setText(iuc.getAno() + YEAR);
        semesterLabel.setText(iuc.getSemestre() + SEMESTER);
        cuLabel.setText(iuc.getNome());
        
        shiftLabel.setText(turno);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
